---
title: "week_4"
author: "Vivian Peregrino"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Code for week 4! Updating past week's code to be more efficient. yay!

```{r loading in data and packages, echo= FALSE, warning = FALSE, include= FALSE}
library(readxl)
library(tidyverse)
library(plotly)
library(dplyr)
library(tigris)
library(paletteer)
library(ggplot2)
library(sf)
library(readr)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
library(maps)
library(tools)

setwd("~/DSPG/Repose/DSPG_VCE_Health/Data")

#Reading in map 
va.counties <- readRDS(file = "va.counties.Rdata")
va.counties$GEOID <- as.integer(va.counties$GEOID)
us.states <- readRDS(file= "us.states.RData")

#County Health Rankings 2023 Data
all_var_path <- "~/DSPG/Repose/DSPG_VCE_Health/Data/final_variables.csv"
all_var_df <- read.csv(paste(all_var_path, sep = ''))
names(all_var_df)[names(all_var_df) == 'FIPS'] <- 'GEOID'
all_var_df$Value <- as.numeric(all_var_df$Value)

#FCS Agent Location Data
agent_path <- "~/DSPG/Repose/DSPG_VCE_Health/Data/vce_agents.csv"
agents_df <- read.csv(paste(agent_path, sep = ''))

#substance abuse treatment centers
treatment_centers_path <- "~/DSPG/Repose/DSPG_VCE_Health/Data/FindTreament_Facility_listing_2023.csv"
treatment_centers <- read.csv(treatment_centers_path)

#making agents and removing missing values
agents_df <- agents_df %>%
  slice(-n())

#converting agents into sf
agents_sf <- st_as_sf(agents_df, coords = c("Long", "Lat"), remove = FALSE, 
    crs = 4326, agr = "constant")
#variable names for title
  good_names <- c("Percent Low Birthweight", "Percent of Adults Reporting Currently Smoking",
                "Percent Population with Access to Exercise Opportunities", "Percent Excessive Drinking",
                "Percent Driving Deaths with Alcohol Involvement", "Dentist Ratio", "Mental Health Provider Ratio", "Teen Birth Rate","Percent Unemployed", "Percent Children in Poverty", "Chlamydia Rate", "Percent Uninsured","Primary Care Physicians Ratio", "Preventable Hospitalization Rate", "Percent With Annual Mammogram",
"Percent Vaccinated", "Life Expectancy", "Life Expectancy Black", "Life Expectancy White",
"Life Expectancy Gap", "Percent of Uninsured Adults", "Percent Uninsured Children", "Other Primary Care Provider Ratio","Drug Mortality Rate", "Percent of Adults With Obesity", "Percent Physically Inactive", "Percent of Adults with Diabetes", "HIV Prevalence Rate","Percent Food Insecure", "Percent Physical Distress", "Percent Physical Distress", "Percent Mental Distress", "Percent Severe Housing Problems", "Percent Insufficient Sleep","Suicide Rate", "Percent Access to Exercise Opportunities","Percent Limited Access to Healthy Foods", "Juvenile Arrests Rate","Percent less than 18 years of age", "Percent 65 and over", "Percent Black", "Percent American Indian or Alaska Native", "Percent Asian","Percent Hispanic","Percent Nonhispanic-White","Percent not Proficient in English","Percent Household Income Required for Child Care Expenses","Gender Pay Gap","Median Household Income Black", "Median Household Income White","Median Household Income Hispanic","Median Household Income Gap White Black","Median Household Income Gap White Hispanic", "Median Household Income")
```

```{r mapping fun, warning = FALSE}
mapping <- function(variable, year) {
  temp <- all_var_df[all_var_df$Year == year & all_var_df$Variable == variable, ]
  var.counties <- left_join(va.counties, temp, by = 'GEOID')
  idx <- which(unique(all_var_df$Variable) == variable)
  ggplot(data = var.counties) +
    geom_sf(data = us.states, color= "grey60", fill= "ivory1") +
    geom_sf(data = var.counties$geometry) +
    geom_sf(data= var.counties, aes(fill= Value))+
    scale_fill_viridis_c(trans= "sqrt", alpha= .4, direction= -1) +
    labs(fill= good_names[idx])+geom_sf(data = agents_sf, aes( color = "red")) +
    guides(color= guide_legend(title= "Agent Sites")) +
    coord_sf(xlim = c(-84, -75), ylim = c(36, 40), expand = FALSE) +
    xlab("Longitude") + ylab("Latitude") +
    ggtitle(paste("VCE FCS Agent Sites and",good_names[idx], year, sep= " ")) +
    theme(panel.grid.major = element_line(color = gray(0.5), 
    linetype = "dashed", size = 0.5),
    panel.background = element_rect(fill = "azure1")) 
}
```

```{r map example, warning = FALSE}
mapping("per_vaccinated", "2020")
```

```{r bargraphs by region}
region_path <- "~/DSPG/Repose/DSPG_VCE_Health/Data/vce_regions.csv"
region_df <- read.csv(paste(region_path, sep = ''))

counties_by_region <- left_join(all_var_df, region_df, by = 'County')

# I got these values from calculating them in a csv
exercise_avg <- c(50.7, 70.0, 73.6, 66.1, 74.2)
Regions <- c("Central", "Northwest", "Northeast", "Southeast", "Southwest")

exercise <- data.frame(cbind(exercise_avg, Regions))

exercise_bar <-ggplot(exercise, aes(x=regions, y=exercise_avg, fill= Regions)) + 
  geom_bar(stat = "identity")+ ggtitle("Percent with Access to Exercise Opportunities 2019")+
  xlab("Region") + ylab("Percent with Access")+
  scale_fill_manual(values= c("cornflowerblue", "lightpink1", "lightcyan", "plum2", "slategray2"))
exercise_bar 

obesity_avg <- c(38.1 , 33.6, 32.3, 37.3, 35.1)
obesity <- data.frame(cbind(obesity_avg, Regions))

obesity_bar <-ggplot(obesity, aes(x=regions, y=obesity_avg, fill= Regions)) + 
  geom_bar(stat = "identity")+ ggtitle("Percent of Adults with Obesity 2019")+
  xlab("Region") + ylab("Percent of Adults with Obesity") +
    scale_fill_manual(values= c("cornflowerblue", "lightpink1", "lightcyan", "plum2", "slategray2"))
obesity_bar

inactivity_avg <- c(32.3, 28.5, 26.5, 30.4, 31.1)
inactivity <- data.frame(cbind(inactivity_avg, Regions))

inactivity_bar <-ggplot(obesity, aes(x=regions, y=inactivity_avg, fill= Regions)) + 
  geom_bar(stat = "identity")+ ggtitle("Percent Physically Inactive 2019")+
  xlab("Region") + ylab("Percent Physically Inactive") +
  scale_fill_manual(values= c("cornflowerblue", "lightpink1", "lightcyan", "plum2", "slategray2"))

inactivity_bar
```

```{r demo pie}
demo <- c(19.2, 0.6, 7.2, 0.1, 10.2, 60.3)
races <- c("Black", "American Indian or Alaska Native", "Asian", "Native Hawaiian or Other Pacific Islander", "Hispanic", "Non-Hispanic White")
demographics <- data.frame(cbind(demo, races))

fig <- plot_ly(demographics, labels = ~races, values = ~demo, type = 'pie')
fig <- fig %>% layout(title = 'Virginia Demographics in 2021',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig
```